/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const bar_Logic = require('./code/bar-logic');
const bingo = require('./code/bingo');

class couleConsumerService extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Bar', async (request, next) => {
            await bar_Logic(request);
            return next();
        });

        const messaging = await cds.connect.to('messaging')
        messaging.on('bingo', async msg => {
          console.log('> received', msg)
          return bingo(this, msg);
        })

        return super.init();
    }
}


module.exports = {
    couleConsumerService
};