/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const foo_Producer = require('./code/foo-producer');

class couleService extends LCAPApplicationService {
    async init() {

        this.before('READ', 'Foo', async (request) => {
            await foo_Producer(request, this);
        });

        return super.init();
    }
}


module.exports = {
    couleService
};